### ISSUE TITLE
Support for associative array 

### ISSUE THREAD

**Issue by rajakvk** [humanwhocodes/array-with-default#3]
Below test failing
```javascript
const items = [1, 2, 3];
items['special'] = 'Special';
expect(itemsWithDefault['special']).to.equal('Special');
```
Please refer screen shots below
![image](https://user-images.githubusercontent.com/120031/130775794-0cd8bc19-7833-4074-b246-60ecf4389488.png)

![image](https://user-images.githubusercontent.com/120031/130776082-87e1f546-9425-4cf2-a4d3-87ff43b89db1.png)

**Comment by nzakas** [comment]
That's beyond the scope of this project.
